spring:
  application:
    name: eureka
  #定义用户名密码
  security:
    user:
      name: admin
      password: admin


server:
  port: 1801

eureka:
  instance:
    #30秒发送1次心跳
    lease-renewal-interval-in-seconds: 30
    #60秒检查1次心跳
    lease-expiration-duration-in-seconds: 60

  server:
    #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    #清理失效服务的间隔30秒1次
    eviction-interval-timer-in-ms: 30000

  client:
    fetch-registry: true
    registry-with-eureka: true
    serviceUrl:
          defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

peer1:
  hostname: eureka1
peer2:
  hostname: eureka2
peer3:
  hostname: eureka3
