server:
  port: ${peer2.port}

eureka:
  instance:
    hostname: ${peer2.hostname}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${peer1.hostname}:${peer1.port}/eureka/, http://${spring.security.user.name}:${spring.security.user.password}@${peer3.hostname}:${peer3.port}/eureka/
